{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "my-api-key",
    "namespace": "default"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "my-api-key",
        "namespace": "default"
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "api-key": "AgA1xCEGiTtdO8iwZQ6dwQeJedu4SyN5czbIkCdukKpO7aHYexJgJZcq5IuRpDZIlr5Q3w1qkNnt7kOwiXaIG9zz8Tuzikd1zkz0dOTxBwCZ72JdeKTRHkKu/4aHog1RprfqRCNomq9p1gw+I2SrpMB3Ci1jZT5/k61gCyCjiZNdgcUMLQAY8HlFfkRSlK9BBmVMo275EqE9vUMbjlBSt/dbAL1aj7QnwrXRfAsMbHSx1CT3YuchOqkPAdGke1SWTZMP9wAd3GjHlZYQto+5xKBEXTI3D2HvHurRh/p7m0JH+a+pbAV2sUy2iP2OQt3s/nOO9+lI6TBiMPOch6/nZWwfJ1zUIsrn2L8Ts41Yg4ZZNubeM2LDKHG5/n06qyD/W+5+0XhWC1ujF8jwb2cX1aM1kLZGAyrhhi5RSdizb28DZJagK0B/TpGbdkikEGiQ/cE3K6Pf5+ockhc3TEWm9Ts0lAtZpDE1gVsqYOuc1K2X92hk6vLxnLEwcsa6RuFqrI4AGOwpE58UviAl5zrEUY/pVhjJ62EHz1mK1qc6xWf5r5U3wcuahTDrMjZ6K6n+SvAT0n0e51jPZWNyF2U//SawqxTJITtMoMwalh/F6rgShWfon06L+rApgN8aqCbGzzBZFqKkMrVJzp8REIO1YMNNKvYCqe895Xx2kNMWdhBobCp22XzW4YYbeT1Ic9NPwcqSat9J2i/TgMdD84d4nSl2+5F3"
    }
  }
}
