apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 26.0.0
    helm:
      releaseName: traefik
      values: |
        deployment:
          kind: DaemonSet

        service:
          type: LoadBalancer

        ports:
          web:
            port: 80
            exposedPort: 80
          websecure:
            port: 443
            exposedPort: 443

        ingressRoute:
          dashboard:
            enabled: true
            matchRule: Host(`traefik.homelab.local`)
            entryPoints: ["websecure"]

        logs:
          general:
            level: INFO
          access:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        maxDuration: 3m
