apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quickwit
  namespace: monitoring
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: quickwit.homelab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quickwit-searcher
                port:
                  number: 7280
